# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sifterology"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ilya Sabanin"]
  s.date = "2013-03-13"
  s.description = "Yeah, that's true."
  s.email = "ilya.sabanin@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/sifterology.rb",
    "lib/sifterology/commit.rb",
    "lib/sifterology/error_translator.rb",
    "lib/sifterology/errors.rb",
    "lib/sifterology/factories/commit_factory.rb",
    "lib/sifterology/factories/project_factory.rb",
    "lib/sifterology/project.rb",
    "lib/sifterology/request.rb",
    "lib/sifterology/resource.rb",
    "lib/sifterology/session.rb",
    "sifterology.gemspec",
    "test/helper.rb",
    "test/test_sifterology.rb"
  ]
  s.homepage = "http://github.com/iSabanin/sifterology"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Quick and dirty API wrapper for Sifter app."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.5"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.5"])
      s.add_runtime_dependency(%q<json>, [">= 1.4.6"])
    else
      s.add_dependency(%q<httparty>, [">= 0.5"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0.5"])
      s.add_dependency(%q<json>, [">= 1.4.6"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.5"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0.5"])
    s.add_dependency(%q<json>, [">= 1.4.6"])
  end
end

