# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sifterology}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ilya Sabanin"]
  s.date = %q{2011-02-18}
  s.description = %q{Yeah, that's true.}
  s.email = %q{ilya.sabanin@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/sifterology.rb",
    "lib/sifterology/commit.rb",
    "lib/sifterology/error_translator.rb",
    "lib/sifterology/errors.rb",
    "lib/sifterology/factories/commit_factory.rb",
    "lib/sifterology/factories/project_factory.rb",
    "lib/sifterology/project.rb",
    "lib/sifterology/request.rb",
    "lib/sifterology/resource.rb",
    "lib/sifterology/session.rb",
    "sifterology.gemspec",
    "test/helper.rb",
    "test/test_sifterology.rb"
  ]
  s.homepage = %q{http://github.com/iSabanin/sifterology}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Quick and dirty API wrapper for Sifter app.}
  s.test_files = [
    "test/helper.rb",
    "test/test_sifterology.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, ["~> 0.6.1"])
      s.add_runtime_dependency(%q<json>, ["~> 1.4.6"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.6.1"])
      s.add_runtime_dependency(%q<json>, [">= 1.4.6"])
    else
      s.add_dependency(%q<httparty>, ["~> 0.6.1"])
      s.add_dependency(%q<json>, ["~> 1.4.6"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0.6.1"])
      s.add_dependency(%q<json>, [">= 1.4.6"])
    end
  else
    s.add_dependency(%q<httparty>, ["~> 0.6.1"])
    s.add_dependency(%q<json>, ["~> 1.4.6"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0.6.1"])
    s.add_dependency(%q<json>, [">= 1.4.6"])
  end
end

